apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-etcd-backup
placementBindingDefaults:
  name: "etcd-backup-binding"
policyDefaults:
  namespace: etcd-backup-policies
  remediationAction: enforce
  policySets:
    - etcd-backup
  severity: medium


policies:

  - name: etcd-backup
    manifests:
      - path: etcd-backup/

policySets:

  - name: etcd-backup
    description: "Perform automated backups of etcd"
    policies:
      - etcd-backup
    placement:
      placementRulePath: "placements/placement-openshift-4.yaml"