apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-backup
  labels:
    app: cronjob-etcd-backup
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sa
    namespace: etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-etcd-backup